---
title: "data-processing"
output: html_document
date: "2024-06-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Packages, echo = FALSE, warning = FALSE, message = FALSE}
# # Load packages -----------------------------------------------------------------------------------
suppressMessages({
  memory.limit(size = 8000000)
  library(readxl)
  library(writexl)
  library(plyr)
  library(dplyr)
  library(data.table)
  library(zoo)
  library(shiny)
  library(shinydashboard)
  library(shinydashboardPlus)
  library(shinyWidgets)
  library(htmlwidgets)
  library(lubridate)
  library(tcltk)
  library(tidyverse)
  library(plotly)
  library(knitr)
  library(kableExtra)
  library(leaflet)
  library(grid)
  library(gridExtra)
  library(eeptools)
  library(ggQC)
  library(zipcodeR)
  library(utils)
  library(scales)
  library(chron)
  library(bupaR)
  library(shiny)
  library(DT)
  library(DiagrammeR)
  library(shinyalert)
  library(edeaR)
  library(processmapR)
  library(processmonitR)
  library(processanimateR)
  library(tidyr)
  library(lubridate)
  library(RColorBrewer)
  library(DiagrammeR)
  library(ggplot2)
  library(leaflet)
  library(readr)
  library(highcharter)
  library(ggforce) # for 'geom_arc_bar'
  library(packcircles) # for packed circle graph
  library(viridis)
  library(ggiraph)
  library(treemapify)
  library(treemap)
  library(broom)
  library(extrafont)
  library(tis) # for US holidays
  library(vroom)
  library(sjmisc)
  library(tools)
  library(here)
  library(shinyBS)
  library(shinyscreenshot)
  library(fasttime)
  library(shinycssloaders)
  library(feather)
  # library(zipcodeR)
  library(formattable)
  library(shinyjs)
  library(janitor)
  library(patchwork)
  library(flexdashboard)
  # library(tidyverse)
  # library(viridis)
  # library(hrbrthemes)
  # library(plotly)
  # install.packages("bsts")
  library(bsts)
  library(reactable)
  # install.packages("reactablefmtr")
  library(reactablefmtr)
  library(svDialogs)
  # library(openxlsx)
  library(flextable)
  library(officedown)
  library(officer)
  library(magrittr)
  library(webshot) 
  library(png)
  library(ggh4x)
  library(RODBC)
  library(DBI)
  library(odbc)
  library(dbplyr)
  library(pool)
  library(emojifont)
})
```


```{r Connection to Oracle, echo = FALSE, warning = FALSE, message = FALSE}

# Connection to Oracle DB ------------------------------------------------------
conn1 <<- dbPool(drv = odbc(), dsn = "OAO Cloud DB Production", timeout = 30)
conn2 <<- dbPool(drv = odbc(), dsn = "OAO Cloud DB SoYoun", timeout = 30)
conn3 <<- dbConnect(odbc(), 
                   "Clarity_prod", 
                   uid = "kweons01" , 
                   pwd = "kweons01123$")

fpax_tbl <<- tbl(conn1, in_schema("OAO_PRODUCTION", "FPAX_MERGED_DETAIL"))
cpsc_benchmark_tbl <- tbl(conn2, "DEV_CPSC_BENCHMARK")

cpsc_benchmark <- cpsc_benchmark_tbl %>% collect()

clarity_ser_tbl <<- tbl(conn3, "CLARITY_SER")
clarity_ser_2_tbl <<- tbl(conn3, "CLARITY_SER_2")

clarity_ser <- clarity_ser_tbl %>%
  dplyr::select(PROV_ID, PROV_TYPE) %>%
  collect()

clarity_ser_2 <- clarity_ser_2_tbl %>%
  dplyr::select(PROV_ID, NPI) %>%
  collect()
```


```{r Mastser Roster, echo = FALSE, warning = FALSE, message = FALSE}

# roster <- read_excel(file.choose(), guess_max = 10000)
# roster <- roster %>% 
#   mutate(PERSON_NUMBER = as.character(PERSON_NUMBER)) %>%
#   filter(`Final Category` != "Inactive")

# med_staff <- read_excel(file.choose())
# 
# med_staff <- med_staff %>%
#   distinct()

```


```{r Allocation Files Received from Departments, echo = FALSE, warning = FALSE, message = FALSE}

allocation_data_raw <- read_excel(file.choose(), sheet = "Master")


# allocation_data_raw$LATEST_HIRE_DATE <- roster$LATEST_HIRE_DATE[match(allocation_data_raw$`Life Number`, roster$PERSON_NUMBER)]
# allocation_data_raw <- allocation_data_raw %>%
#   mutate(LATEST_HIRE_DATE = format(as.Date(LATEST_HIRE_DATE, "%Y-%m-%d"),  "%m/%d/%Y")) %>%
#   mutate(`Hire Date` = ifelse(is.na(`Hire Date`), LATEST_HIRE_DATE, `Hire Date`)) %>%
#   dplyr::select(-LATEST_HIRE_DATE)


allocation_data <- allocation_data_raw %>%
  mutate(hire_org = `Hire Date`,
         term_org = `Term Date`) %>%
  mutate(`Hire Date` = format(as.Date(hire_org , "%m/%d/%Y"), "%m/%d/%Y"),
         `Term Date` = format(as.Date(term_org, "%m/%d/%Y"), "%m/%d/%Y")) %>%
  mutate(`Hire Date` = ifelse(is.na(`Hire Date`), format(as.Date(as.numeric(hire_org), origin="1899-12-30"), "%m/%d/%Y"), `Hire Date`),
         `Term Date` = ifelse(is.na(`Term Date`), format(as.Date(as.numeric(term_org), origin="1899-12-30"), "%m/%d/%Y"), `Term Date`))

cols_include <- c("Master Dept", "CPSC Specialty", "Financial  Site", 
                 "Physician", "NPI", "Life Number", 
                 "Business Unit", "HR Department",  "HR Person Type", "Type", "Type Detail", "Admin Title",
                 "Hire Date", "Term Date", "Year", 
                 "FTE", "Adjusted CFTE",
                 "Clinical", "Clinical With Resident", "Service", "Service With Resident", "Non-Billable Offsite Clinical Time", "Billable Offsite Clinical Time",
                 "Inpatient",  "OR/ Procedures", "Outpatient MSBI", "Outpatient MSB", "Outpatient Chelsea", "Outpatient MSUS", "Outpatient MSDMG",                  
                 "Outpatient MSH-FPA", "Outpatient MSH-AMB CARE", "Outpatient MSW", "Outpatient MSM", "Outpatient NYEE", "Outpatient MSSN", "Outpatient MSQ", "Outpatient NETWORK",
                 "Department/ Hospital Admin", "Residency Program Admin", "Clinical Admin", "Research Funded", "Research Unfunded", "Research Intramurally Funded", "School Teaching",
                 "Final Category", "Notes")

allocation_data_filtered <- allocation_data[cols_include]

new_col_names <- c("MASTER_DEPT", "CPSC_SPECIALTY", "FINANCIAL_SITE", 
                 "PHYSICIAN", "NPI", "LIFE_NUM", 
                 "BUSINESS_UNIT", "HR_DEPARTMENT", "HR_PERSON_TYPE", "TYPE", "TYPE_DETAIL", "ADMIN_TITLE",
                 "HIRE_DATE", "TERM_DATE", "YEAR", 
                 "FTE", "ADJ_CFTE",
                 "CLINICAL", "CLINICAL_RESIDENT", "SERVICE", "SERVICE_RESIDENT", "NON_BILLABLE_OFFSITE_CLINICAL", "BILLABLE_OFFSITE_CLINICAL",
                 "IP", "OR", "OP_MSBI", "OP_MSB", "OP_Chelsea", "OP_MSUS", "OP_MSDMG",                  
                 "OP_MSH_FPA", "OP_MSH_AMB CARE", "OP_MSW", "OP_MSM", "OP_NYEE", "OP_MSSN", "OP_MSQ", "OP_NETWORK",
                 "ADMIN_DEP_HOSP", "ADMIN_RESIDENCY", "ADMIN_CLINICAL", "RESEARCH_FUNDED", "RESEARCH_UNFUNDED", "RESEARCH_INTRAMURAL_FUNDED", "TEACHING", 
                 "FINAL_CATEGORY", "NOTES")

colnames(allocation_data_filtered) <- new_col_names

```


```{r Merge Roster and Allocation Files from Departments, echo = FALSE, warning = FALSE, message = FALSE}

# Identify provideres missing from allocation files submitted by departments
# missing_allocation <- anti_join(roster, allocation_data_filtered, by = c("PERSON_NUMBER" = "LIFE_NUM"))
# missing_allocation_year <- bind_rows(missing_allocation %>% mutate(Year = 2023),
#                                      missing_allocation %>% mutate(Year = 2024)) %>%
#   filter(year(LATEST_HIRE_DATE) <= year(Year)) %>%
#   dplyr::select("Master Department", 
#                 "LIST_NAME",  "NPI", "PERSON_NUMBER",
#                 "BUSINESS_UNIT", "DEPARTMENT", "PERSON_TYPE", 
#                 "LATEST_HIRE_DATE", "Termination Date", "Year",
#                 "FTE",
#                 "Final Category") %>%
#     mutate(LATEST_HIRE_DATE = as.character(LATEST_HIRE_DATE),
#            `Termination Date` = as.character(`Termination Date`),
#            Year = as.character(Year),) %>%
#   mutate(FTE = as.numeric(FTE))
# 
# new_col_names_roster <- c("MASTER_DEPT", 
#                           "PHYSICIAN", "NPI", "LIFE_NUM", 
#                           "BUSINESS_UNIT", "HR_DEPARTMENT", "HR_PERSON_TYPE", 
#                           "HIRE_DATE", "TERM_DATE", "YEAR", 
#                           "FTE", "FINAL_CATEGORY")
# 
# colnames(missing_allocation_year) <- new_col_names_roster
# 
# 
# # Map Provider Type and Name from Clarity SER
# clarity_ser <- clarity_ser_tbl %>%
#   dplyr::select(PROV_ID, PROV_TYPE, PROV_NAME) %>%
#   collect()
# 
# clarity_ser_2 <- clarity_ser_2_tbl %>%
#   filter(!is.na(NPI)) %>%
#   dplyr::select(PROV_ID, NPI) %>%
#   collect()
# 
# missing_allocation_year$PROV_ID <- clarity_ser_2$PROV_ID[match(missing_allocation_year$NPI, clarity_ser_2$NPI)]
# missing_allocation_year$TYPE <- clarity_ser$PROV_TYPE[match(missing_allocation_year$PROV_ID, clarity_ser$PROV_ID)]
# missing_allocation_year$PROV_NAME <- clarity_ser$PROV_NAME[match(missing_allocation_year$PROV_ID, clarity_ser$PROV_ID)]
# 
# missing_allocation_year_CHECK <- missing_allocation_year %>%
#   ungroup() %>%
#   mutate(FINAL_CATEGORY = ifelse(str_detect(FINAL_CATEGORY, "now Vol"), "Voluntary", FINAL_CATEGORY)) %>%
#   mutate(TYPE_DETAIL = ifelse(NPI %in% c("EHC/ QHC", "BS"), NPI, NA),
#          TYPE_DETAIL = ifelse(FINAL_CATEGORY == "Voluntary", "Voluntary", TYPE_DETAIL),
#          NPI = as.character(as.numeric(NPI)),
#          PHYSICIAN = ifelse(is.na(PROV_NAME), toupper(PHYSICIAN), PROV_NAME)) %>%
#   filter(!str_detect(FINAL_CATEGORY, "Inactive"))
```

```{r Merge Merged Allocation Files with FPAX, echo = FALSE, warning = FALSE, message = FALSE}

# allocation_data_merged <- bind_rows(allocation_data_filtered %>% 
#                                       mutate(NPI = as.character(NPI),
#                                              YEAR = as.character(YEAR)), missing_allocation_year)

# allocation_data_merged <- left_join(allocation_data_merged, fpax_data,
#                                     by = c("NPI" = "NPI",
#                                            "YEAR" = "YEAR"))
```

```{r Identify Invalid CPSC Specialty, echo = FALSE, warning = FALSE, message = FALSE}

# productivity_data <- read_excel(file.choose(), sheet = "Master Prod 2024")
# 
# # Map Missing Specialties
# allocation_data_merged <- left_join(allocation_data_merged, productivity_data %>%
#                                       filter(!is.na(NPI)) %>%
#                                       mutate(NPI = as.character(NPI)) %>%
#                                       dplyr::select(NPI, `CPSC Specialty`),
#                                     by = "NPI")
# 
# allocation_data_merged <- allocation_data_merged %>%
#   mutate(CPSC_SPECIALTY = ifelse(is.na(CPSC_SPECIALTY), `CPSC Specialty`, CPSC_SPECIALTY))
# 
# # Filter out invalid CPSC Specialty
# allocation_data_merged <- allocation_data_merged %>%
#   left_join(cpsc_benchmark %>% 
#               mutate(SPECIALTY = SPECIALTY_DESCRIPTION) %>%
#               dplyr::select(SPECIALTY, SPECIALTY_DESCRIPTION), 
#             by = c("CPSC_SPECIALTY" = "SPECIALTY_DESCRIPTION")) %>%
#   mutate(CPSC_SPECIALTY = ifelse(is.na(NPI), NA, SPECIALTY)) %>%
#   ungroup() %>%
#   distinct()
# 
# 
# allocation_data_merged <- allocation_data_merged[c(new_col_names, "WRVU_NUM", "CALC_CHARGE_AMT", "CALC_PAYMENT_AMT")]

```


```{r Create Master Roster, echo = FALSE, warning = FALSE, message = FALSE}

# roster_updated <- allocation_data_merged %>%
#   dplyr::select(MASTER_DEPT, CPSC_SPECIALTY, FINANCIAL_SITE, PHYSICIAN, NPI, LIFE_NUM,
#            BUSINESS_UNIT, HR_DEPARTMENT, HR_PERSON_TYPE, TYPE, TYPE_DETAIL,
#            ADMIN_TITLE, HIRE_DATE, TERM_DATE, FTE) %>%
#   distinct() %>%
#   mutate(LASTE_UPDATED = Sys.Date(),
#          HIRE_DATE = as.Date(HIRE_DATE),
#          TERM_DATE = as.Date(TERM_DATE))


```


```{r Process New Allocation File, echo = FALSE, warning = FALSE, message = FALSE}

# # Identify categories for data validation
# allocation_data_validation <- allocation_data_merged %>%
#   filter(is.na(TERM_DATE) | year(TERM_DATE) >= 2023) %>%
#   map_if(is.numeric,~ifelse(is.na(.x),0,.x)) %>% 
#   as.data.table %>%
#   mutate(MASTER_DEPT = toupper(MASTER_DEPT)) %>%
#   mutate(MASTER_DEPT = ifelse(MASTER_DEPT == "MEDIICINE", "MEDICINE", MASTER_DEPT)) %>%
#   rowwise() %>%
#   mutate(CLINICAL_EFFORT = round(sum(CLINICAL, CLINICAL_RESIDENT, SERVICE, SERVICE_RESIDENT, na.rm = TRUE),2),
#          NON_BILLABLE_CLINICAL_EFFORT = round(sum(NON_BILLABLE_OFFSITE_CLINICAL, na.rm = TRUE),2),
#          ADMIN_EFFORT = round(sum(ADMIN_DEP_HOSP, ADMIN_RESIDENCY, ADMIN_CLINICAL, na.rm = TRUE),2),
#          RESEARCH_EFFORT = round(sum(RESEARCH_FUNDED, RESEARCH_UNFUNDED, RESEARCH_INTRAMURAL_FUNDED, na.rm = TRUE),2),
#          TEACHING_EFFORT = round(TEACHING,2),
#          TOTAL_EFFORT = round(sum(CLINICAL, CLINICAL_RESIDENT, SERVICE, SERVICE_RESIDENT, NON_BILLABLE_OFFSITE_CLINICAL,
#                                       ADMIN_DEP_HOSP, ADMIN_RESIDENCY, ADMIN_CLINICAL, RESEARCH_FUNDED, RESEARCH_UNFUNDED, RESEARCH_INTRAMURAL_FUNDED, TEACHING, na.rm = T),2),
#          TOTAL_CFTE = round(sum(BILLABLE_OFFSITE_CLINICAL, IP, OR, OP_MSBI, OP_MSB, OP_Chelsea, OP_MSUS, OP_MSDMG,                  
#                                             OP_MSH_FPA, `OP_MSH_AMB CARE`, OP_MSW, OP_MSM, OP_NYEE, OP_MSSN, OP_MSQ, OP_NETWORK, na.rm = TRUE),2)) %>%
#   mutate(NO_CPSC_SPECIALTY = ifelse(is.na(CPSC_SPECIALTY), 1, 0),
#          NO_SITE = ifelse(is.na(FINANCIAL_SITE), 1, 0),
#          NO_EFFORT = ifelse(TOTAL_EFFORT == 0, 1, 0),
#          NO_CFTE = ifelse(CLINICAL_EFFORT == 0 & WRVU_NUM > 100, 1, 0),
#          CLINICAL_CFTE_UNMATCH = ifelse(CLINICAL_EFFORT != TOTAL_CFTE, 1, 0),
#          FTE_EFFORT_UNMATCH = ifelse(TOTAL_EFFORT != FTE, 1, 0)
#          ) %>%
#   mutate(VALIDATION_RQEUIRED = ifelse(sum(NO_CPSC_SPECIALTY, NO_EFFORT, NO_CFTE, CLINICAL_CFTE_UNMATCH, FTE_EFFORT_UNMATCH, na.rm = T) > 0, "Y", "N")) %>%
#   mutate(LASTE_UPDATED = Sys.Date(),
#          HIRE_DATE = as.Date(HIRE_DATE),
#          TERM_DATE = as.Date(TERM_DATE)) %>%
#   arrange(MASTER_DEPT, PHYSICIAN, YEAR) 
# 
# 
# 
# 
# allocation_validation_summary <- allocation_data_validation %>%
#   group_by(MASTER_DEPT, TYPE, PHYSICIAN, LIFE_NUM, YEAR, VALIDATION_RQEUIRED) %>%
#   summarise(total = n()) %>%
#   group_by(MASTER_DEPT, TYPE, YEAR, VALIDATION_RQEUIRED) %>%
#   summarise(total = n()) %>%
#   pivot_wider(names_from = VALIDATION_RQEUIRED,
#               values_from = total,
#               values_fill = 0)
# 
# allocation_validation_summary_physicians <- allocation_data_validation %>%
#   filter(TYPE == "Physician" | is.na(TYPE)) %>%
#   group_by(MASTER_DEPT, TYPE, PHYSICIAN, LIFE_NUM, YEAR, VALIDATION_RQEUIRED) %>%
#   summarise(total = n()) %>%
#   group_by(MASTER_DEPT, YEAR, VALIDATION_RQEUIRED) %>%
#   summarise(total = n()) %>%
#   pivot_wider(names_from = VALIDATION_RQEUIRED,
#               values_from = total,
#               values_fill = 0)
```


```{r}

allocation_data_merged <- allocation_data_filtered

provider_roster_dup <- allocation_data_merged %>%
  dplyr::select(MASTER_DEPT, CPSC_SPECIALTY, FINANCIAL_SITE, PHYSICIAN, NPI, LIFE_NUM, 
                BUSINESS_UNIT, HR_DEPARTMENT, HR_PERSON_TYPE, TYPE, TYPE_DETAIL, ADMIN_TITLE, HIRE_DATE, TERM_DATE) %>%
  distinct() %>%
  group_by(PHYSICIAN, NPI, LIFE_NUM) %>%
  mutate(dup = row_number()) 

provider_roster_dup$blanks <-rowSums(is.na(provider_roster_dup))

provider_roster <- provider_roster_dup %>%
  group_by(PHYSICIAN, NPI, LIFE_NUM) %>%
  slice(which.min(blanks)) %>%
  dplyr::select(-c(dup, blanks))

provider_roster_year <- provider_roster[rep(seq_len(nrow(provider_roster)), each = 2), ]
provider_roster_year$YEAR <- rep(c("2023","2024"), nrow(provider_roster))

provider_roster_month <- provider_roster_year[rep(seq_len(nrow(provider_roster_year)), each = 12), ]
provider_roster_month$MONTH <- rep(c("01","02","03","04","05","06","07","08","09","10","11","12"), nrow(provider_roster_year))

provider_roster_final <- provider_roster_month %>%
  mutate(HIRE_DATE_NEW = format(as.Date(HIRE_DATE, "%m/%d/%Y"), "%m/%d/%Y"),
         TERM_DATE_NEW = format(as.Date(TERM_DATE, "%m/%d/%Y"), "%m/%d/%Y")) %>%
  mutate(HIRE_DATE_NEW = ifelse(is.na(HIRE_DATE_NEW), format(as.Date(HIRE_DATE, "%Y-%m-%d"), "%m/%d/%Y"), HIRE_DATE_NEW),
         TERM_DATE_NEW = ifelse(is.na(TERM_DATE_NEW), format(as.Date(TERM_DATE, "%Y-%m-%d"), "%m/%d/%Y"), TERM_DATE_NEW)) %>%
  mutate(EXCLUDE_HIRE = case_when(is.na(HIRE_DATE_NEW) ~ "N",
                            as.Date(paste0(MONTH,"/01/",YEAR), "%m/%d/%Y") < as.Date(HIRE_DATE_NEW,,"%m/%d/%Y") ~ "Y",
                             TRUE ~ "N")) %>%
  mutate(EXCLUDE_TERM = case_when(is.na(TERM_DATE_NEW) ~ "N",
                            as.Date(paste0(MONTH,"/01/",YEAR), "%m/%d/%Y")>= as.Date(TERM_DATE_NEW,,"%m/%d/%Y") ~ "Y",
                             TRUE ~ "N")) %>%
  filter(EXCLUDE_TERM == "N" | EXCLUDE_HIRE == "N") %>%
  mutate(HIRE_DATE = HIRE_DATE_NEW,
         TERM_DATE = TERM_DATE_NEW) %>%
  dplyr::select(-c(HIRE_DATE_NEW, TERM_DATE_NEW, EXCLUDE_TERM, EXCLUDE_HIRE)) 
  
```


```{r}

oracle_data <- provider_roster_final %>%
  left_join(allocation_data_merged %>%
              mutate(YEAR = as.character(YEAR)) %>%
              dplyr::select(-c(MASTER_DEPT, CPSC_SPECIALTY, FINANCIAL_SITE, 
                               BUSINESS_UNIT, HR_DEPARTMENT, HR_PERSON_TYPE, TYPE, TYPE_DETAIL, ADMIN_TITLE, HIRE_DATE, TERM_DATE)),
            by = c("PHYSICIAN", "NPI", "LIFE_NUM", "YEAR")) %>%
  mutate(YEARMO = paste0(YEAR,ifelse(nchar(MONTH) == 1, paste0("0",MONTH), MONTH)),
         LAST_UPDATED = Sys.Date())
```






